name: Release to SPM
on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: 'The version/tag of the release'
                required: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout main branch
            uses: actions/checkout@v4
            with:
                ref: main

          - name: Create new branch
            run: |
                git checkout -b update-release

          - name: Download latest XCUI framework & DocC archive
            env:
                DQ_AGORA_KEY: ${{ secrets.DQ_AGORA_KEY }}
            run: |
                sh .github/scripts/DownloadLatestFrameworkAndDocs.sh ${{ github.event.inputs.releaseVersion }}

          - name: Replace existing XCUI framework & DocC archive
            run: |
                ls .
                pwd

